apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: pdsapp-ssl
  name: pdsapp-ssl
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pdsapp-ssl
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pdsapp-ssl
    spec:
      containers:
      - image: edzlabs/sat_demo:26
        imagePullPolicy: Always
        name: pdsapp-ssl
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-docs
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
